.

diff --git a/.github/workflows/cleanup.yml b/.github/workflows/cleanup.yml
--- a/.github/workflows/cleanup.yml
+++ b/.github/workflows/cleanup.yml
@@ -36,15 +36,14 @@ jobs:
       - name: Request active server files
         # filter out which items from the second list are missing from the base list
         run: |
-            FILES="add.more.languages allows.all.languages catland.social test.com european.server for.testing loony.tunes mastodon.social mstdn.srvr other.server server.something test.server"
-            MISSING=$(grep -vxf <(echo "$FILES" | tr ' ' '\n') <(echo "$domains" | tr ' ' '\n') || true)
-
-            if [ -z "$MISSING" ]; then
-              echo "all elements from server domains are in FILES"
-            else
-              MISSING_SPACE=$(echo "$MISSING" | tr '\n' ' ')
-              echo "missing elements $MISSING_SPACE"
-            fi
+          FILES="add.more.languages allows.all.languages catland.social test.com european.server for.testing loony.tunes mastodon.social mstdn.srvr other.server server.something test.server"
+          MISSING=$(grep -vxf <(echo "$FILES" | tr ' ' '\n') <(echo "$domains" | tr ' ' '\n') || true)
+          if [ -z "$MISSING" ]; then
+            echo "all elements from server domains are in FILES"
+          else
+            MISSING_SPACE=$(echo "$MISSING" | tr '\n' ' ')
+            echo "missing elements $MISSING_SPACE"
+          fi
         shell: bash
       - name: Remove Test file
         run: |
